#!/usr/bin/env bash
set -exuo pipefail

# Setup a raspberry pi as an ethernet bridge. E.g., you connect your pi to a
# wifi network and anything connected to its ethernet will share that
# connection.

# Thank you Pathead for the instructions:
# https://www.raspberrypi.org/forums/viewtopic.php?t=132674

apt update
apt install -y dnsmasq

cat > /etc/network/interfaces.d/ifcfg-eth0 <<ETH0
allow-hotplug eth0
iface eth0 inet static
    address 10.0.0.22
    netmask 255.255.255.0
    network 10.0.0.0
    broadcast 10.0.0.255
ETH0

cat > /etc/dnsmasq.conf <<DNSMASQ
interface=eth0
listen-address=10.0.0.1
bind-interfaces
server=1.1.1.1
domain-needed
bogus-priv
dhcp-range=10.0.0.150,10.0.0.200,12h
DNSMASQ

sudo systemctl enable dnsmasq

echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-eth0_bridge.conf
sysctl -p

# You'll need to switch back to legacy iptables
update-alternatives --set iptables /usr/sbin/iptables-legacy

echo "If you get errors here about a missing module, you need to reboot and run again."
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
iptables-save > /etc/iptables.ipv4.nat
echo 'iptables-restore < /etc/iptables.ipv4.nat' >> /lib/dhcpcd/dhcpcd-hooks/70-ipv4-nat
